# The default config file is based on a criteria for a Drupal project

# enable a log file
log_enabled: no
log_path: "hackedcode-scanner.log"

# the names of the enabled plugins
plugins_enabled:
  - git
  - shell
  - perms

plugin_config:
  git:
    excluded_files: []
  shell:
    excluded_files:
    - modules/
    - core/scripts/
    - core/tests
    - vendor
    - ".git/"
    patterns:
    - '(/usr|/usr/local)?/bin/(ba|da|z|t|tc)?sh ?'
    - ' [A-Za-z0-9 _\-.]+\.sh '
  perms:
    excluded_files:
    - ".git/"
    - "vendor/"
    - core/scripts/
  extensions:
    target_paths:
    - "sync/"
    - "sites/*/files/*"
    target_extensions:
    - '.sh'
    - '.php'
    - '.py'
    excluded_paths:
    - sync/php/twig/*
